### ISSUE TITLE
Better closing bracket detection

### ISSUE THREAD

**Issue by mrwest808** [viablelab/bracket-padder#4]
Ensure the plugin detects when to close brackets properly, right now it won't work when having any other type of [default pairs](https://github.com/viablelab/bracket-padder/blob/786a781/lib/bracket-padder.coffee#L18) between brackets. Example:

Cursor position: `|`

`[ class "container"| ]` + <kbd>]</kbd> should result in `[ class "container" ]|` instead of `[ class "container"]| ]`

**Comment by phyllisstein** [comment]
Noticed this with `{ foo: 'bar'} }` but you beat me to it. 😃 

![screenflow](https://cloud.githubusercontent.com/assets/2207980/21722986/d44f1950-d3fc-11e6-86ea-04e4d4345260.gif)

**Comment by mrwest808** [comment]
Haven't gotten around to fixing this yet since I don't encounter it much in my daily work. I'll try releasing a fix for this in the upcoming days! 🙂

**Comment by mrwest808** [comment]
@phyllisstein I just published a [new version](https://github.com/viablelab/bracket-padder/releases/tag/v0.4.0) that should fix this!

**Comment by phyllisstein** [comment]
Amazing! Thanks so much for your work on this package, it's a life-saver.
