### ISSUE TITLE
Editor freezing when replacing ] with } on first column

### ISSUE THREAD

**Issue by doktordata** [viablelab/bracket-padder#5]
<img width="482" alt="screen shot 2017-01-05 at 14 35 19" src="https://cloud.githubusercontent.com/assets/20992527/21682413/b3c4ecc6-d354-11e6-911c-38298b4ab3a9.png">

Unbelievable!

**Comment by mrwest808** [comment]
Good catch! I've published a [patch](https://github.com/viablelab/bracket-padder/releases/tag/v0.3.6) that should fix this.

**Comment by doktordata** [comment]
mr west, you are the best!
