### ISSUE TITLE
automatic add space on a bracket on parenthesis or optional character

### ISSUE THREAD

**Issue by pmgouveia** [viablelab/bracket-padder#8]
is it possible that the space does not need to be hit? it is automatically insert? :) 

thanks.. cool package!

**Comment by mrwest808** [comment]
I think this would be unexpected behavior for many without flexible options. One way to add this behavior is directly in [Atom's Init file](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/). I've created a [snippet here](https://github.com/viablelab/bracket-padder/wiki#automatically-pad-brackets) that you can use, I'll paste the complete snippet below too.

```coffee
adviseBefore = (object, methodName, advice) ->
  original = object[methodName]
  object[methodName] = (args...) ->
    unless advice.apply(this, args) == false
      original.apply(this, args)

atom.workspace.observeTextEditors (editor) ->
  paddableCharacters =
    '(': ')'
    '[': ']'
    '{': '}'

  autoPadCharacters = (text) ->
    closingCharacter = paddableCharacters[text]
    return true unless closingCharacter

    editor.insertText("#{text}  #{closingCharacter}")
    editor.moveLeft(2)

    false

  adviseBefore(editor, 'insertText', autoPadCharacters)
```

I'll close this issue for now, but let me know if you run into any problems with the snippet!
